#!/usr/bin/env php
<?php
/*
 *  ............(¯''•.
 *  ..............(¯'•(¯'•............_/)/)
 *  ...............(¯'•.(¯'•.......((.....((
 *  ................(¯''•(¯'•...((.)..(. ' /)
 *  .................(¯''•.(¯'((.)....|\_/
 *  .....,,,~”¯¯¯''¯(_,'(_.)......|
 *  ...(((./...........................)__
 *  ..((((.\......),,...........(...../__'\
 *  ..))))..\ . .//...¯¯¯¯¯¯¯' \.../... / /
 *  .(((...../ .// .............. | ./...../
 *  .))).....| ||.................| |...........♥♥♥
 *  ((........) \.................) \...........\|/
 *  .^^^^.""'"'.^^^^^^^..""".^^^^.""""
 *  ( ͡° ͜ʖ ͡°( ಠ ͜ʖ ಠ ) ͡° ͜ʖ ͡°) ( ͡° ͜ʖ ͡°( ಠ ͜ʖ ಠ ) ͡° ͜ʖ ͡°) ( ͡° ͜ʖ ͡°( ಠ ͜ʖ ಠ ) ͡° ͜ʖ ͡°)
 *  ≧◔◡◔≦ ≧◔◡◔≦ ≧◔◡◔≦ ≧◔◡◔≦ ≧◔◡◔≦ ≧◔◡◔≦ ≧◔◡◔≦ ≧◔◡◔≦
 *  
 *  Copyright © 2009-2024 Lê Duy Khoa. All rights reserved.
 *  Mail: leduykhoa060690@gmail.com
 *  Skype: leduykhoa060690
 *  Mobile: +84973421508
 *  Website: https://web-fast.com
 *  Telegram: https://t.me/leduykhoa
 *  GitHub: https://github.com/leduykhoa
 *  Date: 2024/08/06
 *  Time: 16:29:30
 */

require_once('./config/const.php');
require_once('./lib/include.php');

array_shift($argv);

// print_r($argv);
$controllerName = '';
$methodName = '';
if (!isset($argv[0]) || $argv[0] == '') {
    die('Controller name empty');
}
$controllerName = $argv[0];
if (!isset($argv[1]) || $argv[1] == '') {
    die('Method name empty');
}
$methodName = $argv[1];
array_shift($argv);
array_shift($argv);

// Include controller and run
include_once(PATH_CONTROLLER . DS . 'Cmd' . DS . 'CmdController.php');
include_once(PATH_CONTROLLER . DS . 'Cmd' . DS . ucwords(str_replace("\\", DS, $controllerName)) . 'Controller.php');
$klass = 'App\Controllers\\Cmd\\' . ucwords($controllerName) . 'Controller';
$controller = new $klass;
call_user_func_array([$controller, $methodName], $argv);
exit();
implode('&', $argv);
